remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Dice Crunch"
description: "A dice-rolling calculator for your tabletop games!"
author:
  name: "Daniel Arbach"

# Do not change the following line.
  copyright: true
